#use_frameworks!
inhibit_all_warnings!

def commonPods
    pod 'Masonry'
    pod 'YYWebImage'
    pod 'YYCategories'
    pod 'JLRoutes'
    pod 'YYModel'
    pod 'GSToast', :git => 'http://Justin.Wang@gitlab.goshare2.net/Justin.Wang/GSToast.git'
    pod 'YTKNetwork'
    pod 'FDFullscreenPopGesture'
    pod 'WebViewJavascriptBridge'
    pod 'MQTTClient'
end

target 'SmartHome' do
    commonPods
end

